### PR TITLE
podspec

### PR DESCRIPTION
**Pull request by djhr**

### CODE REVIEW

**Comment by yousefhamza** [comment]
Those file will be linked to the react native iOS project when you run:
`react-native link instabug-reactnative`

**Comment by djhr** [comment]
`react-native link instabug-reactnative` will link the module to the ios/android project, not generate the podspec file. For people linking the modules via cocoapods (instead of `react-native link`) this podspec file is needed. Have a look at other modules and you will see that most of them provide a podspec file, even react native itself provide a podspec (https://github.com/facebook/react-native/blob/master/React.podspec) to link it via cocoapods

**Comment by djhr** [comment]
@yousefhamza any update on this?

**Comment by djhr** [comment]
@DevHossamHassan can you have a look at this PR, I think @yousefhamza didn't understand the value/purpose of it so it was closed. Linking modules via cocoapods is very common, and I think would be great this module to support it too.

**Comment by yousefhamza** [comment]
@djhr I'm afraid it doesn't work for us.

The React Pod you refer to is now deprecated and it's version doesn't satisfy our minimum requirement for React, also adding it in a pod cause name conflicts between React in Pods directory and React in node_modules directory

**Comment by djhr** [comment]
@yousefhamza sorry for the delay getting back to you.

> The React Pod you refer to is now deprecated and it's version doesn't satisfy our minimum requirement for React

On the podspec file you can specify which version of the dependency you want, e.g.
`s.dependency 'Instabug', '~> 7.0'` or
`s.dependency 'Instabug ~> 7.0'` not sure which one it is, but one of the two works

> adding it in a pod cause name conflicts between React in Pods directory and React in node_modules directory

My guess is you mixed `react-native link` with podspec. When you opt for podspec as your installation method you need to do it for everything, including react native lib itself, e.g.

```
platform :ios, '8.0'

target 'Sample' do
  use_frameworks!

  # Pods for Sample
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTPushNotification',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'instabug-reactnative', :path => '../node_modules/instabug-reactnative'

  target 'SampleTests' do
    inherit! :search_paths
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTPushNotification',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]
  end

end
```

Also important, after you do `pod init` you should start using the .xcworkspace file to open the project on xcode instead of .xcodeproj file

Some helpful resources:
http://facebook.github.io/react-native/releases/0.47/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies

As last note, I have it working on a project, so it has to be a matter of configuration/steps

**Comment by salmatarzi** [comment]
@djhr  


> On the podspec file you can specify which version of the dependency you want, e.g.
s.dependency 'Instabug', '~> 7.0' or
s.dependency 'Instabug ~> 7.0' not sure which one it is, but one of the two works

The latest React pod version released is below our latest minimum requirement for React as dependency
 

> My guess is you mixed react-native link with podspec. When you opt for podspec as your installation method you need to do it for everything, including react native lib itself, e.g.

In the podspec file, you cannot specify the path as shown in your example, this could be done in the Podfile itself.

**Pull request closed without merging**
