### PR TITLE
Expose disable() to JS side

### PR DESCRIPTION
**Pull request by jozan**

### CODE REVIEW

**Comment by jozan** [comment]
Will this get merged any time soon? :)

**Comment by jozan** [comment]
No updates on this at all?

**Comment by msoliman** [comment]
@jozan very sorry for the delay. I'll look into it and get back to you

**Comment by DevHossamHassan** [comment]
Hello @jozan,
First of all, Sorry for the delay
We've just released a new version contains the `Instabug.enable();` and `Instabug.disable();` APIs version `v1.1.1`
and so far they work only on `android` since we don't have them on the native `iOS` SDK.

So we'll close this PR since it's missing the `enable` API and the platform validation. 
Thank you for your patience.

**Comment by jozan** [comment]
Yay, finally `.disable()`! I'd like to have it in iOS too since it's quite handy. :)

Thanks for not closing the PR without a comment.

**Pull request closed without merging**
